// main.js — Entry point for Phase 6: Sprites, Animations & Visual Identity.

import { entities, getEntity } from './entities.js';
import { drainActions } from './actions.js';
import { setupInput, sampleInput, getMiningState } from './input.js';
import { processActions, update, drainOutboundActions } from './update.js';
import { render } from './render.js';
import { setupNetwork, getLocalPlayerId, sendAction } from './network.js';
import { CANVAS_WIDTH, CANVAS_HEIGHT, BG_COLOR } from './config.js';
import { preloadAllCharacters } from './assetLoader.js';
import { getSlots, getSelectedSlot, HOTBAR_SLOTS } from './inventory.js';
import { TILE_COLORS } from './world.js';

/** How often (seconds) to broadcast our position + velocity for drift correction. */
const POSITION_SYNC_INTERVAL = 0.1;

/** How often (seconds) to recount players for HUD status text. */
const STATUS_SAMPLE_INTERVAL = 0.2;

(async function boot() {
  // Phase 6 — preload all AutoSprite character spritesheets before the game loop starts.
  // This is fast since assets are served locally from assets/sprites/.
  await preloadAllCharacters();

  const app = createApp();
  const { worldLayer, darknessLayer, hudLayer } = createLayers(app.stage);

  setupInput();
  setupNetwork();

  const { statusText, updateHotbar } = buildHud(hudLayer);

  let lastTimestamp = performance.now();
  let syncTimer = 0;
  let statusTimer = STATUS_SAMPLE_INTERVAL; // force immediate first sample
  let cachedPlayerCount = 0;
  const statusState = { text: '', fill: -1 };

  app.ticker.add(() => {
    const now = performance.now();
    const dt = (now - lastTimestamp) / 1000;
    lastTimestamp = now;

    const localId = getLocalPlayerId();

    if (localId !== null) {
      // Local input (MOVE, JUMP, BOOST, BREAK_TILE, PLACE_TILE)
      const localActions = sampleInput(localId, dt);
      for (let i = 0; i < localActions.length; i++) {
        sendAction(localActions[i]);
      }

      // Periodic position + velocity broadcast
      syncTimer += dt;
      if (syncTimer >= POSITION_SYNC_INTERVAL) {
        syncTimer -= POSITION_SYNC_INTERVAL;
        const player = getEntity(localId);
        if (player) {
          sendAction({
            type:     'POSITION',
            entityId: localId,
            x:        player.position.x,
            y:        player.position.y,
            vx:       player.velocity?.x ?? 0,
            vy:       player.velocity?.y ?? 0,
          });
        }
      }
    } else {
      syncTimer = 0;
    }

    // Core loop
    const actions = drainActions();
    processActions(actions);
    update(dt);

    // Actions generated by update (e.g., pickup collection) also go to server
    const outboundActions = drainOutboundActions();
    for (let i = 0; i < outboundActions.length; i++) {
      sendAction(outboundActions[i]);
    }

    render(worldLayer, darknessLayer, entities, getMiningState());

    // Hotbar — update every frame (cheap Graphics redraw)
    updateHotbar();

    // HUD status (lighter than recounting every frame)
    if (localId === null) {
      setStatus(statusText, statusState, 'CONNECTING…', 0x6a6a3a);
    } else {
      statusTimer += dt;
      if (statusTimer >= STATUS_SAMPLE_INTERVAL) {
        statusTimer = 0;
        cachedPlayerCount = countPlayers(entities);
      }

      if (cachedPlayerCount <= 1) {
        setStatus(statusText, statusState, 'ALONE', 0x3a4a6a);
      } else {
        setStatus(statusText, statusState, `${cachedPlayerCount} SOULS`, 0x4a9a6a);
      }
    }
  });
})();

function createApp() {
  const app = new PIXI.Application({
    width:           CANVAS_WIDTH,
    height:          CANVAS_HEIGHT,
    backgroundColor: BG_COLOR,
    antialias:       true,
    resolution:      window.devicePixelRatio || 1,
    autoDensity:     true,
  });

  document.getElementById('game-container').appendChild(app.view);
  return app;
}

function createLayers(stage) {
  const worldLayer    = new PIXI.Container();
  // darknessLayer sits between the world and the HUD so it darkens terrain
  // and entities but never obscures status text or controls hint.
  const darknessLayer = new PIXI.Container();
  const hudLayer      = new PIXI.Container();

  stage.addChild(worldLayer);
  stage.addChild(darknessLayer);
  stage.addChild(hudLayer);

  return { worldLayer, darknessLayer, hudLayer };
}

function buildHud(hudLayer) {
  const style = (size, color, spacing = 1) => ({
    fontFamily:    'monospace',
    fontSize:      size,
    fill:          color,
    letterSpacing: spacing,
  });

  const title = new PIXI.Text('YOU ARE NOT ALONE', style(11, 0x3a4a6a, 3));
  title.x = 16;
  title.y = 14;
  hudLayer.addChild(title);

  const hint = new PIXI.Text(
    'A/D · W/↑ jump · Space boost · LClick mine · RClick place · 1-5 slot',
    style(12, 0x3a4a6a),
  );
  hint.anchor.set(0.5, 1);
  hint.x = CANVAS_WIDTH / 2;
  hint.y = CANVAS_HEIGHT - 14;
  hudLayer.addChild(hint);

  const phase = new PIXI.Text('Phase 6 — Sprites & Animations', style(10, 0x2a3a5a));
  phase.anchor.set(1, 1);
  phase.x = CANVAS_WIDTH - 16;
  phase.y = CANVAS_HEIGHT - 14;
  hudLayer.addChild(phase);

  const statusText = new PIXI.Text('CONNECTING…', style(11, 0x5a6a3a, 2));
  statusText.x = 16;
  statusText.y = 34;
  hudLayer.addChild(statusText);

  // ── Hotbar ────────────────────────────────────────────────────────────────
  const SLOT_SIZE    = 40;
  const SLOT_MARGIN  = 4;
  const HOTBAR_TOTAL = HOTBAR_SLOTS * (SLOT_SIZE + SLOT_MARGIN) - SLOT_MARGIN;
  const hotbarX      = Math.round((CANVAS_WIDTH - HOTBAR_TOTAL) / 2);
  const hotbarY      = CANVAS_HEIGHT - SLOT_SIZE - 40;

  const hotbarGfx   = new PIXI.Graphics();
  const hotbarTexts = [];
  hudLayer.addChild(hotbarGfx);

  for (let i = 0; i < HOTBAR_SLOTS; i++) {
    const tx = hotbarX + i * (SLOT_SIZE + SLOT_MARGIN);

    // Slot number label (top-left corner)
    const numText = new PIXI.Text(`${i + 1}`, {
      fontFamily: 'monospace',
      fontSize:   9,
      fill:       0x778899,
    });
    numText.x = tx + 3;
    numText.y = hotbarY + 3;
    hudLayer.addChild(numText);

    // Item count label (bottom-right corner)
    const countText = new PIXI.Text('', {
      fontFamily: 'monospace',
      fontSize:   10,
      fill:       0xffffff,
    });
    countText.anchor.set(1, 1);
    countText.x = tx + SLOT_SIZE - 3;
    countText.y = hotbarY + SLOT_SIZE - 3;
    hudLayer.addChild(countText);

    hotbarTexts.push({ countText });
  }

  function updateHotbar() {
    hotbarGfx.clear();
    const slots   = getSlots();
    const selSlot = getSelectedSlot();

    for (let i = 0; i < HOTBAR_SLOTS; i++) {
      const sx         = hotbarX + i * (SLOT_SIZE + SLOT_MARGIN);
      const sy         = hotbarY;
      const slot       = slots[i];
      const isSelected = i === selSlot;

      // Slot background
      hotbarGfx.beginFill(0x111118, isSelected ? 0.9 : 0.65);
      hotbarGfx.drawRect(sx, sy, SLOT_SIZE, SLOT_SIZE);
      hotbarGfx.endFill();

      // Border (gold when selected, subtle when not)
      hotbarGfx.lineStyle(isSelected ? 2 : 1, isSelected ? 0xffd700 : 0x445566, 1);
      hotbarGfx.drawRect(sx, sy, SLOT_SIZE, SLOT_SIZE);
      hotbarGfx.lineStyle(0);

      // Item colour swatch
      if (slot.count > 0 && slot.tileType !== 0) {
        const swatchColor = TILE_COLORS[slot.tileType] ?? 0x888888;
        const swatchSize  = 22;
        const swatchX     = sx + (SLOT_SIZE - swatchSize) / 2;
        const swatchY     = sy + (SLOT_SIZE - swatchSize) / 2;
        hotbarGfx.beginFill(swatchColor, 1);
        hotbarGfx.drawRect(swatchX, swatchY, swatchSize, swatchSize);
        hotbarGfx.endFill();
      }

      // Count text
      hotbarTexts[i].countText.text = slot.count > 0 ? String(slot.count) : '';
    }
  }

  return { statusText, updateHotbar };
}

function countPlayers(allEntities) {
  let count = 0;
  for (let i = 0; i < allEntities.length; i++) {
    if (allEntities[i]?.isPlayer) count++;
  }
  return count;
}

function setStatus(statusText, statusState, text, fill) {
  if (statusState.text === text && statusState.fill === fill) return;
  statusText.text       = text;
  statusText.style.fill = fill;
  statusState.text      = text;
  statusState.fill      = fill;
}